info:
  contact: {}
paths:
  /api/v1/medicines:
    get:
      consumes:
      - application/json
      description: Mendapatkan daftar obat (pagination)
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: List Obat
      tags:
      - Medicines
swagger: "2.0"
